GET http://localhost:3000/project
###

GET http://localhost:3000/project/1
###

POST http://localhost:3000/project
Content-Type: application/json

{
    "title": "Project 1"
}
###
DELETE http://localhost:3000/project/4